# Base configs
baseurl: "https://arshakanjum.github.io/portfolio"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio - Arshak Anjum"
author: "Arshak Anjum"
header:
 title: "Portfolio"
 subtitle: " Arshak Anjum"
footer:
 name: "Hey there, my name is Arshak"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life."
 
web_design: "AA"
social_urls:
  facebook: "https://www.facebook.com/musiconarshak"
  instagram: "https://www.instagram.com/arshakanjum"
  github: "https://www.github.com/arshakanjum"
